apiVersion: v1
kind: Service
metadata:
  name: flask-app-stateestimation-deployment
spec:
  selector:
    app: flask-app-stateestimation
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30001
  type: NodePort
