# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Ensure the pyvolt library is included in the Python path
#ENV PYTHONPATH="/app/pyvolt:${PYTHONPATH}"

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 5001 for the state estimation app
EXPOSE 5001

# Run the Flask app when the container launches
CMD ["python", "app_stateestimation.py"]
