apiVersion: v1
kind: Service
metadata:
  name: flask-app-stateestimation-service
spec:
  selector:
    app: flask-app-stateestimation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
      nodePort: 30081
  type: NodePort
