apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-stateestimation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-stateestimation
  template:
    metadata:
      labels:
        app: flask-app-stateestimation
    spec:
      containers:
      - name: flask-app-stateestimation
        image: flask-app-stateestimation:latest
        imagePullPolicy: Never   # Add this line
        ports:
        - containerPort: 5001